/* ============================================== */
/*  Generated by Y Compiler — C11 Backend   */
/* ============================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* ── Y Runtime: String ──────────────────── */
typedef struct {
    char*  data;
    size_t len;
    size_t cap;
} YStr;

static YStr ystr_new(const char* s) {
    size_t len = s ? strlen(s) : 0;
    size_t cap = len + 1;
    char* data = (char*)malloc(cap);
    if (s) memcpy(data, s, len);
    data[len] = '\0';
    return (YStr){ data, len, cap };
}

static YStr ystr_clone(const YStr* s) {
    return ystr_new(s->data);
}

static void ystr_push(YStr* s, char c) {
    if (s->len + 1 >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    s->data[s->len++] = c;
    s->data[s->len] = '\0';
}

static void ystr_push_str(YStr* s, const YStr* other) {
    size_t olen = other->len;
    while (s->len + olen >= s->cap) {
        s->cap = s->cap * 2 + 1;
        s->data = (char*)realloc(s->data, s->cap);
    }
    memcpy(s->data + s->len, other->data, olen);
    s->len += olen;
    s->data[s->len] = '\0';
}

static bool ystr_eq(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static bool ystr_eq_cstr(const YStr* a, const char* b) {
    return strcmp(a->data, b) == 0;
}
static bool ystr_eq_val(const YStr* a, const YStr* b) {
    if (a->len != b->len) return false;
    return memcmp(a->data, b->data, a->len) == 0;
}

static char ystr_char_at(const YStr* s, size_t i) {
    return (i < s->len) ? s->data[i] : '\0';
}

static void ystr_free(YStr* s) {
    free(s->data);
    s->data = NULL;
    s->len = 0;
    s->cap = 0;
}

/* ── Y Runtime: Dynamic Vector ──────────── */
typedef struct {
    void*  data;
    size_t len;
    size_t cap;
    size_t elem_size;
} YVec;

static YVec yvec_new(size_t elem_size) {
    return (YVec){ NULL, 0, 0, elem_size };
}

static void yvec_push(YVec* v, const void* elem) {
    if (v->len >= v->cap) {
        v->cap = v->cap == 0 ? 8 : v->cap * 2;
        v->data = realloc(v->data, v->cap * v->elem_size);
    }
    memcpy((char*)v->data + v->len * v->elem_size, elem, v->elem_size);
    v->len++;
}

static void* yvec_get(const YVec* v, size_t i) {
    return (char*)v->data + i * v->elem_size;
}

static char yvec_get_char(const YVec* v, size_t i) {
    return *((char*)yvec_get(v, i));
}

static size_t yvec_len(const YVec* v) {
    return v->len;
}

static size_t ystr_len(const YStr* s) {
    return s->len;
}

static void yvec_free(YVec* v) {
    free(v->data);
    v->data = NULL;
    v->len = 0;
    v->cap = 0;
}

/* ── Y Runtime: Print ───────────────────── */
static void yprint_str(const YStr* s) {
    printf("%s", s->data);
}

static void yprint_int(int64_t v) {
    printf("%lld", (long long)v);
}

static void yprint_float(double v) {
    printf("%f", v);
}

static void yprintln_str(const YStr* s) {
    printf("%s\n", s->data);
}

/* ── Y Runtime: File I/O ────────────────── */
static YStr yfile_read_to_string(const YStr* path_str) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", path);
        exit(1);
    }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(len + 1);
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    YStr result = { buf, (size_t)len, (size_t)(len + 1) };
    return result;
}

static void yfile_write(const YStr* path_str, const YStr* content) {
    const char* path = path_str->data;
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "Error: Cannot write file '%s'\n", path);
        exit(1);
    }
    fwrite(content->data, 1, content->len, f);
    fclose(f);
}

/* ── User Code ───────────────────────────────── */

/* -- Y Runtime: Vec Set Helpers -- */
static void Vec_set_I8(YVec* v, size_t i, int8_t val) {
    if (i < v->len) {
        ((int8_t*)v->data)[i] = val;
    }
}

static void Vec_set_U32(YVec* v, size_t i, uint32_t val) {
    if (i < v->len) {
        ((uint32_t*)v->data)[i] = val;
    }
}

/* -- Source: aig_minimizer.c -- */



/* Forward declarations for opaque types */
typedef struct AstArena AstArena;

typedef struct AigEdge AigEdge;
typedef struct AigNode AigNode;
typedef struct AigGraph AigGraph;

typedef enum {
    AigNodeKind_TAG_PrimaryInput,
    AigNodeKind_TAG_AndGate,
    AigNodeKind_TAG_Constant
} AigNodeKind_Tag;

typedef struct {
    uint32_t _0;
} AigNodeKind_PrimaryInput_Data;

typedef struct {
    bool _0;
} AigNodeKind_Constant_Data;

typedef struct {
    AigNodeKind_Tag tag;
    union {
        AigNodeKind_PrimaryInput_Data PrimaryInput;
        AigNodeKind_Constant_Data Constant;
    } data;
} AigNodeKind;

static inline AigNodeKind AigNodeKind_PrimaryInput(uint32_t _0) {
    AigNodeKind res;
    res.tag = AigNodeKind_TAG_PrimaryInput;
    res.data.PrimaryInput._0 = _0;
    return res;
}

#define AigNodeKind_AndGate ((AigNodeKind){ .tag = AigNodeKind_TAG_AndGate })
static inline AigNodeKind AigNodeKind_Constant(bool _0) {
    AigNodeKind res;
    res.tag = AigNodeKind_TAG_Constant;
    res.data.Constant._0 = _0;
    return res;
}

struct AigEdge {
    uint32_t target;
    bool complemented;
};

struct AigNode {
    AigNodeKind kind;
    AigEdge input_a;
    AigEdge input_b;
    uint64_t hash;
    bool is_dead;
    uint32_t ref_count;
};

struct AigGraph {
    YVec nodes;
    uint32_t node_count;
    YVec primary_inputs;
    uint32_t pi_count;
    YVec primary_outputs;
    uint32_t po_count;
    YVec hash_table;
    uint32_t hash_capacity;
    uint32_t nodes_pruned;
    uint32_t nodes_deduplicated;
};

AigNode Vec_get_AigNode(const YVec* v, size_t i);
AigEdge Vec_get_AigEdge(const YVec* v, size_t i);
AigGraph AigGraph_new(uint32_t estimated_nodes);
AigEdge AigGraph_add_primary_input(AigGraph* g, uint32_t var_idx);
AigEdge AigGraph_add_constant(AigGraph* g, bool val);
AigEdge AigGraph_add_and(AigGraph* g, AigEdge a, AigEdge b);
void AigGraph_add_primary_output(AigGraph* g, AigEdge edge);
uint32_t AigGraph_prune_dead_nodes(AigGraph* g);
uint32_t AigGraph_count_live_nodes(const AigGraph* g);
void AigGraph_inc_ref(AigGraph* g, uint32_t node_idx);
bool AigGraph_is_primary_output(const AigGraph* g, uint32_t node_idx);
uint64_t AigGraph_compute_and_hash(const AigGraph* g, AigEdge a, AigEdge b);
void AigGraph_print_stats(const AigGraph* g);

/* impl Vec */
AigNode Vec_get_AigNode(const YVec* v, size_t i) {
    AigNode d = {0};
    return d;
}

AigEdge Vec_get_AigEdge(const YVec* v, size_t i) {
    AigEdge d = {0};
    return d;
}

/* impl AigGraph */
AigGraph AigGraph_new(uint32_t estimated_nodes) {
    AigGraph g;
    g.nodes = yvec_new(32);
    g.node_count = 0;
    g.primary_inputs = yvec_new(8);
    g.pi_count = 0;
    g.primary_outputs = yvec_new(8);
    g.po_count = 0;
    g.hash_capacity = (estimated_nodes * 2);
    g.hash_table = yvec_new(8);
    uint32_t i = 0;
    while ((i < g.hash_capacity)) {
        uint32_t sentinel = 4294967295;
        { __typeof__((&sentinel)) __push_tmp = (&sentinel); yvec_push((&g.hash_table), &__push_tmp); };
        i += 1;
    }
    g.nodes_pruned = 0;
    g.nodes_deduplicated = 0;
    return g;
}

AigEdge AigGraph_add_primary_input(AigGraph* g, uint32_t var_idx) {
    AigNode node;
    node.kind = AigNodeKind_PrimaryInput(var_idx);
    node.input_a.target = 0;
    node.input_a.complemented = false;
    node.input_b.target = 0;
    node.input_b.complemented = false;
    node.hash = var_idx;
    node.is_dead = false;
    node.ref_count = 0;
    uint32_t idx = (*g).node_count;
    { __typeof__((&node)) __push_tmp = (&node); yvec_push((&(*g).nodes), &__push_tmp); };
    (*g).node_count += 1;
    { __typeof__((&idx)) __push_tmp = (&idx); yvec_push((&(*g).primary_inputs), &__push_tmp); };
    (*g).pi_count += 1;
    AigEdge edge;
    edge.target = idx;
    edge.complemented = false;
    return edge;
}

AigEdge AigGraph_add_constant(AigGraph* g, bool val) {
    AigNode node;
    node.kind = AigNodeKind_Constant(val);
    node.input_a.target = 0;
    node.input_a.complemented = false;
    node.input_b.target = 0;
    node.input_b.complemented = false;
    node.hash = 0;
    node.is_dead = false;
    node.ref_count = 0;
    uint32_t idx = (*g).node_count;
    { __typeof__((&node)) __push_tmp = (&node); yvec_push((&(*g).nodes), &__push_tmp); };
    (*g).node_count += 1;
    AigEdge edge;
    edge.target = idx;
    edge.complemented = false;
    return edge;
}

AigEdge AigGraph_add_and(AigGraph* g, AigEdge a, AigEdge b) {
    AigNode node_a = (*(AigNode*)yvec_get((&(*g).nodes), a.target));
    AigNode node_b = (*(AigNode*)yvec_get((&(*g).nodes), b.target));
    if ((node_a.kind.tag == AigNodeKind_TAG_Constant)) {
        bool val = node_a.kind.data.Constant._0;
        bool effective = (val ^ a.complemented);
        if ((effective == false)) {
            (*g).nodes_pruned += 1;
            return AigGraph_add_constant(g, false);
        }
        if ((effective == true)) {
            (*g).nodes_pruned += 1;
            return b;
        }
    }
    if ((node_b.kind.tag == AigNodeKind_TAG_Constant)) {
        bool val = node_b.kind.data.Constant._0;
        bool effective = (val ^ b.complemented);
        if ((effective == false)) {
            (*g).nodes_pruned += 1;
            return AigGraph_add_constant(g, false);
        }
        if ((effective == true)) {
            (*g).nodes_pruned += 1;
            return a;
        }
    }
    if ((a.target == b.target)) {
        if ((a.complemented == b.complemented)) {
            (*g).nodes_pruned += 1;
            return a;
        }
        (*g).nodes_pruned += 1;
        return AigGraph_add_constant(g, false);
    }
    AigEdge ca = a;
    AigEdge cb = b;
    if ((ca.target > cb.target)) {
        AigEdge tmp = ca;
        ca = cb;
        cb = tmp;
    }
    uint64_t hash = AigGraph_compute_and_hash(g, ca, cb);
    uint32_t slot = (hash % (*g).hash_capacity);
    uint32_t existing = (*(uint32_t*)yvec_get((&(*g).hash_table), slot));
    if ((existing != 4294967295)) {
        AigNode ex_node = (*(AigNode*)yvec_get((&(*g).nodes), existing));
        if (((((ex_node.input_a.target == ca.target) && (ex_node.input_a.complemented == ca.complemented)) && (ex_node.input_b.target == cb.target)) && (ex_node.input_b.complemented == cb.complemented))) {
            (*g).nodes_deduplicated += 1;
            AigEdge dedup_edge;
            dedup_edge.target = existing;
            dedup_edge.complemented = false;
            return dedup_edge;
        }
    }
    AigNode node;
    node.kind = AigNodeKind_AndGate;
    node.input_a = ca;
    node.input_b = cb;
    node.hash = hash;
    node.is_dead = false;
    node.ref_count = 0;
    uint32_t idx = (*g).node_count;
    { __typeof__((&node)) __push_tmp = (&node); yvec_push((&(*g).nodes), &__push_tmp); };
    (*g).node_count += 1;
    Vec_set_U32((&(*g).hash_table), slot, idx);
    AigGraph_inc_ref(g, ca.target);
    AigGraph_inc_ref(g, cb.target);
    AigEdge edge;
    edge.target = idx;
    edge.complemented = false;
    return edge;
}

void AigGraph_add_primary_output(AigGraph* g, AigEdge edge) {
    { __typeof__((&edge)) __push_tmp = (&edge); yvec_push((&(*g).primary_outputs), &__push_tmp); };
    (*g).po_count += 1;
    AigGraph_inc_ref(g, edge.target);
}

uint32_t AigGraph_prune_dead_nodes(AigGraph* g) {
    uint32_t pruned = 0;
    uint32_t i = 0;
    while ((i < (*g).node_count)) {
        AigNode node = (*(AigNode*)yvec_get((&(*g).nodes), i));
        if ((node.ref_count == 0)) {
            bool is_po = AigGraph_is_primary_output(g, i);
            if ((is_po == false)) {
                node.is_dead = true;
                pruned += 1;
            }
        }
        i += 1;
    }
    (*g).nodes_pruned += pruned;
    return pruned;
}

uint32_t AigGraph_count_live_nodes(const AigGraph* g) {
    uint32_t count = 0;
    uint32_t i = 0;
    while ((i < (*g).node_count)) {
        AigNode node = (*(AigNode*)yvec_get((&(*g).nodes), i));
        if ((node.is_dead == false)) {
            count += 1;
        }
        i += 1;
    }
    return count;
}

void AigGraph_inc_ref(AigGraph* g, uint32_t node_idx) {
    AigNode node = (*(AigNode*)yvec_get((&(*g).nodes), node_idx));
    node.ref_count += 1;
}

bool AigGraph_is_primary_output(const AigGraph* g, uint32_t node_idx) {
    uint32_t i = 0;
    while ((i < (*g).po_count)) {
        AigEdge edge = (*(AigEdge*)yvec_get((&(*g).primary_outputs), i));
        if ((edge.target == node_idx)) {
            return true;
        }
        i += 1;
    }
    return false;
}

uint64_t AigGraph_compute_and_hash(const AigGraph* g, AigEdge a, AigEdge b) {
    uint64_t h = 0;
    h = (h ^ a.target);
    h = (h * 1099511628211);
    h = (h ^ a.complemented);
    h = (h * 1099511628211);
    h = (h ^ b.target);
    h = (h * 1099511628211);
    h = (h ^ b.complemented);
    h = (h * 1099511628211);
    return h;
}

void AigGraph_print_stats(const AigGraph* g) {
    printf("%s", (ystr_new("[AIG] Total nodes: ")).data);
    printf("%d\n", (int)(*g).node_count);
    printf("%s", (ystr_new(" | Pruned: ")).data);
    printf("%d\n", (int)(*g).nodes_pruned);
    printf("%s", (ystr_new(" | Deduplicated: ")).data);
    printf("%d\n", (int)(*g).nodes_deduplicated);
    printf("%s", (ystr_new(" | Live: ")).data);
    printf("%d\n", (int)AigGraph_count_live_nodes(g));
    printf("%s\n", (ystr_new("")).data);
}


/* -- Source: arithmetizer.c -- */



typedef struct VarMapping VarMapping;
typedef struct Clause Clause;
typedef struct AdjacencyMatrix AdjacencyMatrix;
typedef struct Arithmetizer Arithmetizer;
typedef struct DummyArena DummyArena;

struct VarMapping {
    uint32_t ast_id;
    uint32_t matrix_col;
    bool is_negated;
};

struct Clause {
    uint32_t literal_start;
    uint32_t literal_count;
    uint32_t row_idx;
};

struct AdjacencyMatrix {
    YVec data;
    uint32_t rows;
    uint32_t cols;
    uint32_t num_clauses;
    uint32_t num_variables;
};

struct Arithmetizer {
    YVec var_map;
    uint32_t var_count;
    YVec clauses;
    uint32_t clause_count;
    YVec coeff_buf;
    uint32_t coeff_cap;
    YVec errors;
    uint32_t error_count;
};

struct DummyArena {
    YVec nodes;
    uint32_t count;
};

typedef enum {
    DummyOp_And,
    DummyOp_Or,
    DummyOp_Not
} DummyOp;

typedef enum {
    DummyNode_TAG_Var,
    DummyNode_TAG_BinOp,
    DummyNode_TAG_UnaryNot
} DummyNode_Tag;

typedef struct {
    char _0;
} DummyNode_Var_Data;

typedef struct {
    DummyOp _0;
    uint32_t _1;
    uint32_t _2;
} DummyNode_BinOp_Data;

typedef struct {
    uint32_t _0;
} DummyNode_UnaryNot_Data;

typedef struct {
    DummyNode_Tag tag;
    union {
        DummyNode_Var_Data Var;
        DummyNode_BinOp_Data BinOp;
        DummyNode_UnaryNot_Data UnaryNot;
    } data;
} DummyNode;

static inline DummyNode DummyNode_Var(char _0) {
    DummyNode res;
    res.tag = DummyNode_TAG_Var;
    res.data.Var._0 = _0;
    return res;
}

static inline DummyNode DummyNode_BinOp(DummyOp _0, uint32_t _1, uint32_t _2) {
    DummyNode res;
    res.tag = DummyNode_TAG_BinOp;
    res.data.BinOp._0 = _0;
    res.data.BinOp._1 = _1;
    res.data.BinOp._2 = _2;
    return res;
}

static inline DummyNode DummyNode_UnaryNot(uint32_t _0) {
    DummyNode res;
    res.tag = DummyNode_TAG_UnaryNot;
    res.data.UnaryNot._0 = _0;
    return res;
}

VarMapping Vec_get_VarMapping(const YVec* v, size_t i);
Clause Vec_get_Clause(const YVec* v, size_t i);
AdjacencyMatrix AdjacencyMatrix_new(uint32_t num_clauses, uint32_t num_variables);
Arithmetizer Arithmetizer_new(uint32_t max_variables);
uint32_t Arithmetizer_register_variable(Arithmetizer* ar, uint32_t ast_id);
void Arithmetizer_arith_and(Arithmetizer* ar, uint32_t col_a, uint32_t col_b);
void Arithmetizer_arith_or(Arithmetizer* ar, uint32_t col_a, uint32_t col_b);
void Arithmetizer_arith_not(Arithmetizer* ar, uint32_t col);
uint32_t Arithmetizer_flatten_expr(Arithmetizer* ar, const AstArena* arena, size_t expr_idx);
void Arithmetizer_emit_clause(Arithmetizer* ar, const AstArena* arena, size_t expr_idx, AdjacencyMatrix* out);
uint32_t Arithmetizer_name_to_id(const Arithmetizer* ar, const YStr* name);
DummyNode Vec_get_DummyNode(const YVec* v, size_t i);
DummyArena DummyArena_new(void);
uint32_t DummyArena_push_node(DummyArena* da, DummyNode node);
DummyArena build_dummy_ast(void);
DummyArena build_not_test_ast(void);
uint32_t flatten_dummy(Arithmetizer* ar, const DummyArena* da, uint32_t node_idx);
void print_matrix(const AdjacencyMatrix* mat);
void print_coeff_buf(const Arithmetizer* ar);
void run_arithmetizer_test(void);

static const int8_t BOOL_FALSE = 0;

static const int8_t BOOL_TRUE = 1;

static const int8_t BOOL_UNASSIGNED = (-1);

/* impl Vec */
VarMapping Vec_get_VarMapping(const YVec* v, size_t i) {
    VarMapping d = {0};
    return d;
}

/* impl Vec */
Clause Vec_get_Clause(const YVec* v, size_t i) {
    Clause d = {0};
    return d;
}

/* impl AdjacencyMatrix */
AdjacencyMatrix AdjacencyMatrix_new(uint32_t num_clauses, uint32_t num_variables) {
    AdjacencyMatrix mat;
    size_t total = (num_clauses * num_variables);
    mat.data = yvec_new(1);
    size_t i = 0;
    while ((i < total)) {
        int8_t zero = 0;
        { __typeof__((&zero)) __push_tmp = (&zero); yvec_push((&mat.data), &__push_tmp); };
        i += 1;
    }
    mat.rows = num_clauses;
    mat.cols = num_variables;
    mat.num_clauses = num_clauses;
    mat.num_variables = num_variables;
    return mat;
}

/* impl Arithmetizer */
Arithmetizer Arithmetizer_new(uint32_t max_variables) {
    Arithmetizer ar;
    ar.var_map = yvec_new(8);
    ar.var_count = 0;
    ar.clauses = yvec_new(16);
    ar.clause_count = 0;
    ar.coeff_buf = yvec_new(1);
    ar.coeff_cap = max_variables;
    uint32_t i = 0;
    while ((i < max_variables)) {
        int8_t zero = 0;
        { __typeof__((&zero)) __push_tmp = (&zero); yvec_push((&ar.coeff_buf), &__push_tmp); };
        i += 1;
    }
    ar.errors = yvec_new(8);
    ar.error_count = 0;
    return ar;
}

uint32_t Arithmetizer_register_variable(Arithmetizer* ar, uint32_t ast_id) {
    uint32_t i = 0;
    while ((i < (*ar).var_count)) {
        VarMapping entry = (*(VarMapping*)yvec_get((&(*ar).var_map), i));
        if ((entry.ast_id == ast_id)) {
            return entry.matrix_col;
        }
        i += 1;
    }
    uint32_t col = (*ar).var_count;
    VarMapping mapping;
    mapping.ast_id = ast_id;
    mapping.matrix_col = col;
    mapping.is_negated = false;
    { __typeof__((&mapping)) __push_tmp = (&mapping); yvec_push((&(*ar).var_map), &__push_tmp); };
    (*ar).var_count += 1;
    return col;
}

void Arithmetizer_arith_and(Arithmetizer* ar, uint32_t col_a, uint32_t col_b) {
    int8_t val_a = (*(int8_t*)yvec_get((&(*ar).coeff_buf), col_a));
    int8_t val_b = (*(int8_t*)yvec_get((&(*ar).coeff_buf), col_b));
    int8_t product = (val_a * val_b);
    Vec_set_I8((&(*ar).coeff_buf), col_a, product);
    int8_t zero = 0;
    Vec_set_I8((&(*ar).coeff_buf), col_b, zero);
}

void Arithmetizer_arith_or(Arithmetizer* ar, uint32_t col_a, uint32_t col_b) {
    int8_t val_a = (*(int8_t*)yvec_get((&(*ar).coeff_buf), col_a));
    int8_t val_b = (*(int8_t*)yvec_get((&(*ar).coeff_buf), col_b));
    int8_t product = (val_a * val_b);
    int8_t result = ((val_a + val_b) - product);
    Vec_set_I8((&(*ar).coeff_buf), col_a, result);
    int8_t zero = 0;
    Vec_set_I8((&(*ar).coeff_buf), col_b, zero);
}

void Arithmetizer_arith_not(Arithmetizer* ar, uint32_t col) {
    int8_t val = (*(int8_t*)yvec_get((&(*ar).coeff_buf), col));
    int8_t complement = (1 - val);
    Vec_set_I8((&(*ar).coeff_buf), col, complement);
}

/* Stubbed out — these functions depend on Y compiler AST types (Expr, BinaryOp, UnaryOp)
   which are not available in the Z3 integration context. Z3 feeds raw CNF clauses directly
   to booledass_solve(), bypassing the Arithmetizer AST-to-matrix path. */
uint32_t Arithmetizer_flatten_expr(Arithmetizer* ar, const AstArena* arena, size_t expr_idx) {
    (void)ar; (void)arena; (void)expr_idx;
    return 0;
}

void Arithmetizer_emit_clause(Arithmetizer* ar, const AstArena* arena, size_t expr_idx, AdjacencyMatrix* out) {
    (void)ar; (void)arena; (void)expr_idx; (void)out;
}

uint32_t Arithmetizer_name_to_id(const Arithmetizer* ar, const YStr* name) {
    size_t len = ystr_len(name);
    if ((len == 0)) {
        return 0;
    }
    uint32_t hash = 2166136261;
    size_t i = 0;
    while ((i < len)) {
        char ch = ystr_char_at(name, i);
        hash = (hash ^ ch);
        hash = (hash * 16777619);
        i += 1;
    }
    return hash;
}

/* impl Vec */
DummyNode Vec_get_DummyNode(const YVec* v, size_t i) {
    DummyNode d = {0};
    return d;
}

/* impl DummyArena */
DummyArena DummyArena_new(void) {
    DummyArena da;
    da.nodes = yvec_new(16);
    da.count = 0;
    return da;
}

uint32_t DummyArena_push_node(DummyArena* da, DummyNode node) {
    uint32_t idx = (*da).count;
    { __typeof__((&node)) __push_tmp = (&node); yvec_push((&(*da).nodes), &__push_tmp); };
    (*da).count += 1;
    return idx;
}

DummyArena build_dummy_ast(void) {
    DummyArena da = DummyArena_new();
    uint32_t a = DummyArena_push_node((&da), DummyNode_Var('A'));
    uint32_t b = DummyArena_push_node((&da), DummyNode_Var('B'));
    uint32_t c = DummyArena_push_node((&da), DummyNode_Var('C'));
    uint32_t b_or_c = DummyArena_push_node((&da), DummyNode_BinOp(DummyOp_Or, b, c));
    uint32_t root = DummyArena_push_node((&da), DummyNode_BinOp(DummyOp_And, a, b_or_c));
    return da;
}

DummyArena build_not_test_ast(void) {
    DummyArena da = DummyArena_new();
    uint32_t a = DummyArena_push_node((&da), DummyNode_Var('A'));
    uint32_t b = DummyArena_push_node((&da), DummyNode_Var('B'));
    uint32_t not_a = DummyArena_push_node((&da), DummyNode_UnaryNot(a));
    uint32_t root = DummyArena_push_node((&da), DummyNode_BinOp(DummyOp_And, not_a, b));
    return da;
}

uint32_t flatten_dummy(Arithmetizer* ar, const DummyArena* da, uint32_t node_idx) {
    DummyNode node = (*(DummyNode*)yvec_get((&(*da).nodes), node_idx));
    if ((node.tag == DummyNode_TAG_Var)) {
        char ch = node.data.Var._0;
        uint32_t id = (ch - 'A');
        uint32_t col = Arithmetizer_register_variable(ar, id);
        int8_t one = 1;
        Vec_set_I8((&(*ar).coeff_buf), col, one);
        return col;
    }
    if ((node.tag == DummyNode_TAG_BinOp)) {
        DummyOp op = node.data.BinOp._0;
        uint32_t lhs = node.data.BinOp._1;
        uint32_t rhs = node.data.BinOp._2;
        uint32_t col_l = flatten_dummy(ar, da, lhs);
        uint32_t col_r = flatten_dummy(ar, da, rhs);
        if ((op == DummyOp_And)) {
            Arithmetizer_arith_and(ar, col_l, col_r);
            return col_l;
        }
        if ((op == DummyOp_Or)) {
            Arithmetizer_arith_or(ar, col_l, col_r);
            return col_l;
        }
        return col_l;
    }
    if ((node.tag == DummyNode_TAG_UnaryNot)) {
        uint32_t operand = node.data.UnaryNot._0;
        uint32_t col = flatten_dummy(ar, da, operand);
        Arithmetizer_arith_not(ar, col);
        return col;
    }
    return 0;
}

void print_matrix(const AdjacencyMatrix* mat) {
    printf("%s", (ystr_new("[booledass] Adjacency Matrix (")).data);
    printf("%d\n", (int)(*mat).rows);
    printf("%s", (ystr_new(" clauses x ")).data);
    printf("%d\n", (int)(*mat).cols);
    printf("%s\n", (ystr_new(" variables):")).data);
    uint32_t r = 0;
    while ((r < (*mat).rows)) {
        printf("%s", (ystr_new("  Row ")).data);
        printf("%d\n", (int)r);
        printf("%s", (ystr_new(": [ ")).data);
        uint32_t c = 0;
        while ((c < (*mat).cols)) {
            uint32_t idx = ((r * (*mat).cols) + c);
            int8_t val = (*(int8_t*)yvec_get((&(*mat).data), idx));
            if ((val >= 0)) {
                printf("%s", (ystr_new(" ")).data);
            }
            printf("%d\n", (int)val);
            printf("%s", (ystr_new(" ")).data);
            c += 1;
        }
        printf("%s\n", (ystr_new("]")).data);
        r += 1;
    }
}

void print_coeff_buf(const Arithmetizer* ar) {
    printf("%s", (ystr_new("[booledass] Coefficients (")).data);
    printf("%d\n", (int)(*ar).var_count);
    printf("%s", (ystr_new(" vars): [ ")).data);
    uint32_t i = 0;
    while ((i < (*ar).var_count)) {
        int8_t val = (*(int8_t*)yvec_get((&(*ar).coeff_buf), i));
        if ((val >= 0)) {
            printf("%s", (ystr_new(" ")).data);
        }
        printf("%d\n", (int)val);
        printf("%s", (ystr_new(" ")).data);
        i += 1;
    }
    printf("%s\n", (ystr_new("]")).data);
}

void run_arithmetizer_test(void) {
    printf("%s\n", (ystr_new("═══════════════════════════════════════════════════")).data);
    printf("%s\n", (ystr_new("[booledass] Arithmetizer CPU Smoke Test")).data);
    printf("%s\n", (ystr_new("═══════════════════════════════════════════════════")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] -- Test 1: A AND (B OR C) --")).data);
    DummyArena da1 = build_dummy_ast();
    Arithmetizer ar1 = Arithmetizer_new(8);
    uint32_t c1 = 0;
    while ((c1 < 8)) {
        int8_t zero = 0;
        Vec_set_I8((&ar1.coeff_buf), c1, zero);
        c1 += 1;
    }
    uint32_t root1 = (da1.count - 1);
    uint32_t result_col1 = flatten_dummy((&ar1), (&da1), root1);
    printf("%s", (ystr_new("[booledass]   Result column: ")).data);
    printf("%d\n", (int)result_col1);
    printf("%s\n", (ystr_new("")).data);
    print_coeff_buf((&ar1));
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] -- Test 2: NOT(A) AND B --")).data);
    DummyArena da2 = build_not_test_ast();
    Arithmetizer ar2 = Arithmetizer_new(8);
    uint32_t c2 = 0;
    while ((c2 < 8)) {
        int8_t zero = 0;
        Vec_set_I8((&ar2.coeff_buf), c2, zero);
        c2 += 1;
    }
    uint32_t root2 = (da2.count - 1);
    uint32_t result_col2 = flatten_dummy((&ar2), (&da2), root2);
    printf("%s", (ystr_new("[booledass]   Result column: ")).data);
    printf("%d\n", (int)result_col2);
    printf("%s\n", (ystr_new("")).data);
    print_coeff_buf((&ar2));
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] -- Combined Matrix (2 clauses) --")).data);
    uint32_t max_vars = 3;
    AdjacencyMatrix mat = AdjacencyMatrix_new(2, max_vars);
    uint32_t v = 0;
    while ((v < ar1.var_count)) {
        int8_t coeff = (*(int8_t*)yvec_get((&ar1.coeff_buf), v));
        Vec_set_I8((&mat.data), v, coeff);
        v += 1;
    }
    Arithmetizer ar2b = Arithmetizer_new(8);
    uint32_t c2b = 0;
    while ((c2b < 8)) {
        int8_t zero = 0;
        Vec_set_I8((&ar2b.coeff_buf), c2b, zero);
        c2b += 1;
    }
    flatten_dummy((&ar2b), (&da2), (da2.count - 1));
    uint32_t row1_base = max_vars;
    uint32_t v2 = 0;
    while ((v2 < ar2b.var_count)) {
        int8_t coeff = (*(int8_t*)yvec_get((&ar2b.coeff_buf), v2));
        Vec_set_I8((&mat.data), (row1_base + v2), coeff);
        v2 += 1;
    }
    print_matrix((&mat));
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] Arithmetizer smoke test complete.")).data);
    printf("%s\n", (ystr_new("═══════════════════════════════════════════════════")).data);
}


/* -- Source: wmma_core.c -- */



typedef struct PaddedMatrix PaddedMatrix;
typedef struct AccumulatorTile AccumulatorTile;
typedef struct WmmaAllocator WmmaAllocator;
typedef struct MmaDispatch MmaDispatch;
typedef struct CpuPaddedMatrix CpuPaddedMatrix;

struct PaddedMatrix {
    uint64_t dev_ptr;
    uint32_t padded_rows;
    uint32_t padded_cols;
    uint32_t logical_rows;
    uint32_t logical_cols;
    uint32_t ld;
    uint64_t byte_size;
};

struct AccumulatorTile {
    uint64_t dev_ptr;
    uint32_t rows;
    uint32_t cols;
    uint32_t ld;
    uint64_t byte_size;
};

struct WmmaAllocator {
    uint64_t vram_budget;
    uint64_t vram_used;
    uint32_t alloc_count;
    YVec alloc_ptrs;
};

struct MmaDispatch {
    uint32_t tile_m;
    uint32_t tile_n;
    uint32_t tile_k;
};

struct CpuPaddedMatrix {
    YVec data;
    uint32_t logical_rows;
    uint32_t logical_cols;
    uint32_t padded_rows;
    uint32_t padded_cols;
};

WmmaAllocator WmmaAllocator_new(uint64_t budget);
uint32_t WmmaAllocator_align_to_tile(uint32_t dim, uint32_t tile);
PaddedMatrix WmmaAllocator_allocate_padded(WmmaAllocator* wa, uint32_t logical_rows, uint32_t logical_cols);
AccumulatorTile WmmaAllocator_allocate_accumulator(WmmaAllocator* wa, uint32_t rows, uint32_t cols);
void WmmaAllocator_upload_matrix(WmmaAllocator* wa, const AdjacencyMatrix* src, const PaddedMatrix* dst);
void WmmaAllocator_free_all(WmmaAllocator* wa);
uint64_t WmmaAllocator_cuda_malloc(WmmaAllocator* wa, uint64_t bytes);
void WmmaAllocator_cuda_free(WmmaAllocator* wa, uint64_t ptr);
void WmmaAllocator_cuda_memset(WmmaAllocator* wa, uint64_t ptr, int8_t val, uint64_t bytes);
void WmmaAllocator_cuda_memset_i32(WmmaAllocator* wa, uint64_t ptr, int32_t val, uint64_t count);
void WmmaAllocator_cuda_memcpy_h2d(WmmaAllocator* wa, uint64_t dst, uint64_t src_offset, uint64_t bytes);
MmaDispatch MmaDispatch_new(void);
void MmaDispatch_mma_sync_i8(const MmaDispatch* dispatch, uint64_t a_smem_ptr, uint64_t b_smem_ptr, uint64_t c_ptr, uint64_t d_ptr, uint32_t a_ld, uint32_t b_ld);
void MmaDispatch_matmul_tiled(const MmaDispatch* dispatch, const PaddedMatrix* a, const PaddedMatrix* b, AccumulatorTile* c);
CpuPaddedMatrix CpuPaddedMatrix_pad_matrix_cpu(const YVec* src_data, uint32_t logical_rows, uint32_t logical_cols, uint32_t tile_rows, uint32_t tile_cols);
void print_padded_matrix(const CpuPaddedMatrix* pm);
void run_padder_test(void);

static const uint32_t WMMA_M = 16;

static const uint32_t WMMA_N = 8;

static const uint32_t WMMA_K = 16;

static const int8_t IDENTITY_SINK = 0;

/* impl WmmaAllocator */
WmmaAllocator WmmaAllocator_new(uint64_t budget) {
    WmmaAllocator wa;
    wa.vram_budget = budget;
    wa.vram_used = 0;
    wa.alloc_count = 0;
    wa.alloc_ptrs = yvec_new(8);
    return wa;
}

uint32_t WmmaAllocator_align_to_tile(uint32_t dim, uint32_t tile) {
    uint32_t remainder = (dim % tile);
    if ((remainder == 0)) {
        return dim;
    }
    return (dim + (tile - remainder));
}

PaddedMatrix WmmaAllocator_allocate_padded(WmmaAllocator* wa, uint32_t logical_rows, uint32_t logical_cols) {
    uint32_t pr = WmmaAllocator_align_to_tile(logical_rows, WMMA_M);
    uint32_t pc = WmmaAllocator_align_to_tile(logical_cols, WMMA_K);
    uint64_t total_elements = (pr * pc);
    uint64_t byte_size = total_elements;
    if ((((*wa).vram_used + byte_size) > (*wa).vram_budget)) {
        printf("%s", (ystr_new("[!] BooledAss VRAM budget exceeded: ")).data);
        printf("%d\n", (int)((*wa).vram_used + byte_size));
        printf("%s", (ystr_new(" > ")).data);
        printf("%d\n", (int)(*wa).vram_budget);
        printf("%s\n", (ystr_new(" bytes")).data);
        PaddedMatrix null_mat;
        null_mat.dev_ptr = 0;
        null_mat.padded_rows = 0;
        null_mat.padded_cols = 0;
        null_mat.logical_rows = logical_rows;
        null_mat.logical_cols = logical_cols;
        null_mat.ld = 0;
        null_mat.byte_size = 0;
        return null_mat;
    }
    uint64_t dev_addr = WmmaAllocator_cuda_malloc(wa, byte_size);
    WmmaAllocator_cuda_memset(wa, dev_addr, IDENTITY_SINK, byte_size);
    { __typeof__((&dev_addr)) __push_tmp = (&dev_addr); yvec_push((&(*wa).alloc_ptrs), &__push_tmp); };
    (*wa).alloc_count += 1;
    (*wa).vram_used += byte_size;
    PaddedMatrix pmat;
    pmat.dev_ptr = dev_addr;
    pmat.padded_rows = pr;
    pmat.padded_cols = pc;
    pmat.logical_rows = logical_rows;
    pmat.logical_cols = logical_cols;
    pmat.ld = pc;
    pmat.byte_size = byte_size;
    return pmat;
}

AccumulatorTile WmmaAllocator_allocate_accumulator(WmmaAllocator* wa, uint32_t rows, uint32_t cols) {
    uint32_t pr = WmmaAllocator_align_to_tile(rows, WMMA_M);
    uint32_t pc = WmmaAllocator_align_to_tile(cols, WMMA_N);
    uint64_t total = (pr * pc);
    uint64_t byte_size = (total * 4);
    uint64_t dev_addr = WmmaAllocator_cuda_malloc(wa, byte_size);
    WmmaAllocator_cuda_memset_i32(wa, dev_addr, 0, total);
    { __typeof__((&dev_addr)) __push_tmp = (&dev_addr); yvec_push((&(*wa).alloc_ptrs), &__push_tmp); };
    (*wa).alloc_count += 1;
    (*wa).vram_used += byte_size;
    AccumulatorTile acc;
    acc.dev_ptr = dev_addr;
    acc.rows = pr;
    acc.cols = pc;
    acc.ld = pc;
    acc.byte_size = byte_size;
    return acc;
}

void WmmaAllocator_upload_matrix(WmmaAllocator* wa, const AdjacencyMatrix* src, const PaddedMatrix* dst) {
    uint32_t r = 0;
    while ((r < (*src).rows)) {
        uint64_t src_offset = (r * (*src).cols);
        uint64_t dst_offset = (r * (*dst).ld);
        WmmaAllocator_cuda_memcpy_h2d(wa, ((*dst).dev_ptr + dst_offset), src_offset, (*src).cols);
        r += 1;
    }
}

void WmmaAllocator_free_all(WmmaAllocator* wa) {
    uint32_t i = 0;
    while ((i < (*wa).alloc_count)) {
        uint64_t ptr = (*(uint64_t*)yvec_get((&(*wa).alloc_ptrs), i));
        WmmaAllocator_cuda_free(wa, ptr);
        i += 1;
    }
    (*wa).vram_used = 0;
    (*wa).alloc_count = 0;
}

uint64_t WmmaAllocator_cuda_malloc(WmmaAllocator* wa, uint64_t bytes) {
    return 0;
}

void WmmaAllocator_cuda_free(WmmaAllocator* wa, uint64_t ptr) {
}

void WmmaAllocator_cuda_memset(WmmaAllocator* wa, uint64_t ptr, int8_t val, uint64_t bytes) {
}

void WmmaAllocator_cuda_memset_i32(WmmaAllocator* wa, uint64_t ptr, int32_t val, uint64_t count) {
}

void WmmaAllocator_cuda_memcpy_h2d(WmmaAllocator* wa, uint64_t dst, uint64_t src_offset, uint64_t bytes) {
}

/* impl MmaDispatch */
MmaDispatch MmaDispatch_new(void) {
    MmaDispatch d = {0};
    d.tile_m = WMMA_M;
    d.tile_n = WMMA_N;
    d.tile_k = WMMA_K;
    return d;
}

/* @ptx_emit */
void MmaDispatch_mma_sync_i8(const MmaDispatch* dispatch, uint64_t a_smem_ptr, uint64_t b_smem_ptr, uint64_t c_ptr, uint64_t d_ptr, uint32_t a_ld, uint32_t b_ld) {
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile (".reg .b32 %ra<4>;");
        asm volatile (".reg .b32 %rb<2>;");
        asm volatile (".reg .s32 %rc<4>;");
        asm volatile (".reg .s32 %rd<4>;");
        asm volatile (".reg .b64 %addr_a, %addr_b, %addr_c, %addr_d;");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: .reg .b32 %ra<4>; */
    /* PTX: .reg .b32 %rb<2>; */
    /* PTX: .reg .s32 %rc<4>; */
    /* PTX: .reg .s32 %rd<4>; */
    /* PTX: .reg .b64 %addr_a, %addr_b, %addr_c, %addr_d; */
    #endif
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile ("// [BooledAss] Load A fragment: 16x16 I8 from SMEM");
        asm volatile ("mov.b64 %addr_a, %0;");
        asm volatile ("ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%ra0, %ra1, %ra2, %ra3}, [%addr_a];");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: // [BooledAss] Load A fragment: 16x16 I8 from SMEM */
    /* PTX: mov.b64 %addr_a, %0; */
    /* PTX: ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%ra0, %ra1, %ra2, %ra3}, [%addr_a]; */
    #endif
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile ("// [BooledAss] Load B fragment: 16x8 I8 from SMEM");
        asm volatile ("mov.b64 %addr_b, %1;");
        asm volatile ("ldmatrix.sync.aligned.m8n8.x2.shared.b16 {%rb0, %rb1}, [%addr_b];");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: // [BooledAss] Load B fragment: 16x8 I8 from SMEM */
    /* PTX: mov.b64 %addr_b, %1; */
    /* PTX: ldmatrix.sync.aligned.m8n8.x2.shared.b16 {%rb0, %rb1}, [%addr_b]; */
    #endif
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile ("// [BooledAss] Load C accumulator: 16x8 I32");
        asm volatile ("mov.b64 %addr_c, %2;");
        asm volatile ("ld.shared.v4.s32 {%rc0, %rc1, %rc2, %rc3}, [%addr_c];");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: // [BooledAss] Load C accumulator: 16x8 I32 */
    /* PTX: mov.b64 %addr_c, %2; */
    /* PTX: ld.shared.v4.s32 {%rc0, %rc1, %rc2, %rc3}, [%addr_c]; */
    #endif
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile ("// [BooledAss] ═══ TENSOR CORE MMA ═══");
        asm volatile ("// D[16x8] = A[16x16] * B[16x8] + C[16x8]");
        asm volatile ("// Boolean domain: A,B ∈ {0,1} as I8, C,D ∈ Z as I32");
        asm volatile ("mma.sync.aligned.m16n8k16.row.col.s32.s8.s8.s32");
        asm volatile ("  {%rd0, %rd1, %rd2, %rd3},");
        asm volatile ("  {%ra0, %ra1, %ra2, %ra3},");
        asm volatile ("  {%rb0, %rb1},");
        asm volatile ("  {%rc0, %rc1, %rc2, %rc3};");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: // [BooledAss] ═══ TENSOR CORE MMA ═══ */
    /* PTX: // D[16x8] = A[16x16] * B[16x8] + C[16x8] */
    /* PTX: // Boolean domain: A,B ∈ {0,1} as I8, C,D ∈ Z as I32 */
    /* PTX: mma.sync.aligned.m16n8k16.row.col.s32.s8.s8.s32 */
    /* PTX:   {%rd0, %rd1, %rd2, %rd3}, */
    /* PTX:   {%ra0, %ra1, %ra2, %ra3}, */
    /* PTX:   {%rb0, %rb1}, */
    /* PTX:   {%rc0, %rc1, %rc2, %rc3}; */
    #endif
    /* chisel block — PTX inline assembly */
    #if defined(__NVCC__) || defined(__CUDACC__)
    {
        asm volatile ("// [BooledAss] Store D result: 16x8 I32");
        asm volatile ("mov.b64 %addr_d, %3;");
        asm volatile ("st.shared.v4.s32 [%addr_d], {%rd0, %rd1, %rd2, %rd3};");
    }
    #else
    /* PTX asm elided on non-CUDA host target */
    /* PTX: // [BooledAss] Store D result: 16x8 I32 */
    /* PTX: mov.b64 %addr_d, %3; */
    /* PTX: st.shared.v4.s32 [%addr_d], {%rd0, %rd1, %rd2, %rd3}; */
    #endif
}

void MmaDispatch_matmul_tiled(const MmaDispatch* dispatch, const PaddedMatrix* a, const PaddedMatrix* b, AccumulatorTile* c) {
    uint32_t tiles_m = ((*a).padded_rows / WMMA_M);
    uint32_t tiles_n = ((*b).padded_cols / WMMA_N);
    uint32_t tiles_k = ((*a).padded_cols / WMMA_K);
    uint32_t tm = 0;
    while ((tm < tiles_m)) {
        uint32_t tn = 0;
        while ((tn < tiles_n)) {
            uint32_t tk = 0;
            while ((tk < tiles_k)) {
                uint64_t a_offset = (((tm * WMMA_M) * (*a).ld) + (tk * WMMA_K));
                uint64_t b_offset = (((tk * WMMA_K) * (*b).ld) + (tn * WMMA_N));
                uint64_t c_offset = ((((tm * WMMA_M) * (*c).ld) + (tn * WMMA_N)) * 4);
                MmaDispatch_mma_sync_i8(dispatch, ((*a).dev_ptr + a_offset), ((*b).dev_ptr + b_offset), ((*c).dev_ptr + c_offset), ((*c).dev_ptr + c_offset), (*a).ld, (*b).ld);
                tk += 1;
            }
            tn += 1;
        }
        tm += 1;
    }
}

/* impl CpuPaddedMatrix */
CpuPaddedMatrix CpuPaddedMatrix_pad_matrix_cpu(const YVec* src_data, uint32_t logical_rows, uint32_t logical_cols, uint32_t tile_rows, uint32_t tile_cols) {
    uint32_t pr = WmmaAllocator_align_to_tile(logical_rows, tile_rows);
    uint32_t pc = WmmaAllocator_align_to_tile(logical_cols, tile_cols);
    uint32_t total = (pr * pc);
    YVec padded = yvec_new(1);
    uint32_t i = 0;
    while ((i < total)) {
        int8_t zero = 0;
        { __typeof__((&zero)) __push_tmp = (&zero); yvec_push((&padded), &__push_tmp); };
        i += 1;
    }
    uint32_t r = 0;
    while ((r < logical_rows)) {
        uint32_t c = 0;
        while ((c < logical_cols)) {
            uint32_t src_idx = ((r * logical_cols) + c);
            uint32_t dst_idx = ((r * pc) + c);
            int8_t val = (*(int8_t*)yvec_get(src_data, src_idx));
            Vec_set_I8((&padded), dst_idx, val);
            c += 1;
        }
        r += 1;
    }
    CpuPaddedMatrix result;
    result.data = padded;
    result.logical_rows = logical_rows;
    result.logical_cols = logical_cols;
    result.padded_rows = pr;
    result.padded_cols = pc;
    return result;
}

void print_padded_matrix(const CpuPaddedMatrix* pm) {
    printf("%s", (ystr_new("[booledass] Padded Matrix: ")).data);
    printf("%d\n", (int)(*pm).logical_rows);
    printf("%s", (ystr_new("x")).data);
    printf("%d\n", (int)(*pm).logical_cols);
    printf("%s", (ystr_new(" -> ")).data);
    printf("%d\n", (int)(*pm).padded_rows);
    printf("%s", (ystr_new("x")).data);
    printf("%d\n", (int)(*pm).padded_cols);
    printf("%s\n", (ystr_new("")).data);
    uint32_t r = 0;
    while ((r < (*pm).padded_rows)) {
        printf("%s", (ystr_new("  ")).data);
        if ((r < (*pm).logical_rows)) {
            printf("%s", (ystr_new("L")).data);
        } else {
            printf("%s", (ystr_new("P")).data);
        }
        printf("%s", (ystr_new(" Row ")).data);
        if ((r < 10)) {
            printf("%s", (ystr_new(" ")).data);
        }
        printf("%d\n", (int)r);
        printf("%s", (ystr_new(": [")).data);
        uint32_t c = 0;
        while ((c < (*pm).padded_cols)) {
            uint32_t idx = ((r * (*pm).padded_cols) + c);
            int8_t val = (*(int8_t*)yvec_get((&(*pm).data), idx));
            if ((c == (*pm).logical_cols)) {
                printf("%s", (ystr_new("|")).data);
            }
            if ((val >= 0)) {
                printf("%s", (ystr_new(" ")).data);
            }
            printf("%d\n", (int)val);
            c += 1;
        }
        printf("%s\n", (ystr_new(" ]")).data);
        if (((r + 1) == (*pm).logical_rows)) {
            printf("%s", (ystr_new("  ──────── padding boundary ")).data);
            uint32_t dash_count = ((*pm).padded_cols * 3);
            uint32_t d = 0;
            while ((d < dash_count)) {
                printf("%s", (ystr_new("─")).data);
                d += 1;
            }
            printf("%s\n", (ystr_new("")).data);
        }
        r += 1;
    }
}

void run_padder_test(void) {
    printf("%s\n", (ystr_new("═══════════════════════════════════════════════════")).data);
    printf("%s\n", (ystr_new("[booledass] Identity Sink Padder CPU Test")).data);
    printf("%s\n", (ystr_new("═══════════════════════════════════════════════════")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] -- Test 1: 5x5 -> 16x16 --")).data);
    YVec src5 = yvec_new(1);
    uint32_t r5 = 0;
    while ((r5 < 5)) {
        uint32_t c5 = 0;
        while ((c5 < 5)) {
            int8_t val = 0;
            if ((r5 == c5)) {
                val = 1;
            }
            { __typeof__((&val)) __push_tmp = (&val); yvec_push((&src5), &__push_tmp); };
            c5 += 1;
        }
        r5 += 1;
    }
    CpuPaddedMatrix pm5 = CpuPaddedMatrix_pad_matrix_cpu((&src5), 5, 5, WMMA_M, WMMA_K);
    print_padded_matrix((&pm5));
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] -- Test 2: 13x13 -> 16x16 --")).data);
    YVec src13 = yvec_new(1);
    uint32_t r13 = 0;
    while ((r13 < 13)) {
        uint32_t c13 = 0;
        while ((c13 < 13)) {
            int8_t val = 0;
            uint32_t sum = (r13 + c13);
            if (((sum % 2) == 0)) {
                val = 1;
            }
            { __typeof__((&val)) __push_tmp = (&val); yvec_push((&src13), &__push_tmp); };
            c13 += 1;
        }
        r13 += 1;
    }
    CpuPaddedMatrix pm13 = CpuPaddedMatrix_pad_matrix_cpu((&src13), 13, 13, WMMA_M, WMMA_K);
    print_padded_matrix((&pm13));
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] -- Test 3: 16x16 -> 16x16 (no-op) --")).data);
    YVec src16 = yvec_new(1);
    uint32_t r16 = 0;
    while ((r16 < 16)) {
        uint32_t c16 = 0;
        while ((c16 < 16)) {
            int8_t val = 0;
            if ((r16 == c16)) {
                val = 1;
            }
            { __typeof__((&val)) __push_tmp = (&val); yvec_push((&src16), &__push_tmp); };
            c16 += 1;
        }
        r16 += 1;
    }
    CpuPaddedMatrix pm16 = CpuPaddedMatrix_pad_matrix_cpu((&src16), 16, 16, WMMA_M, WMMA_K);
    printf("%s", (ystr_new("[booledass]   padded_rows=")).data);
    printf("%d\n", (int)pm16.padded_rows);
    printf("%s", (ystr_new(" padded_cols=")).data);
    printf("%d\n", (int)pm16.padded_cols);
    printf("%s", (ystr_new(" (expected: 16x16, delta=0)")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] -- Test 4: 7x3 -> 16x16 (non-square) --")).data);
    YVec src73 = yvec_new(1);
    uint32_t r73 = 0;
    while ((r73 < 7)) {
        uint32_t c73 = 0;
        while ((c73 < 3)) {
            int8_t val = 1;
            { __typeof__((&val)) __push_tmp = (&val); yvec_push((&src73), &__push_tmp); };
            c73 += 1;
        }
        r73 += 1;
    }
    CpuPaddedMatrix pm73 = CpuPaddedMatrix_pad_matrix_cpu((&src73), 7, 3, WMMA_M, WMMA_K);
    print_padded_matrix((&pm73));
    printf("%s\n", (ystr_new("")).data);
    printf("%s\n", (ystr_new("[booledass] Padder smoke test complete.")).data);
    printf("%s\n", (ystr_new("═══════════════════════════════════════════════════")).data);
}


/* -- Source: stream_manager.c -- */



typedef struct StreamFence StreamFence;
typedef struct StreamHandle StreamHandle;
typedef struct PipelineSlot PipelineSlot;
typedef struct PcieMetrics PcieMetrics;
typedef struct StreamManager StreamManager;

typedef enum {
    BufferState_Idle,
    BufferState_Filling,
    BufferState_Transferring,
    BufferState_Solving
} BufferState;

struct StreamFence {
    uint64_t event_handle;
    uint64_t stream_handle;
    bool is_recorded;
    uint32_t tag;
};

struct StreamHandle {
    uint32_t slot_index;
    BufferState state;
    uint32_t generation;
    uint64_t host_pinned_ptr;
    uint64_t dev_ptr;
    uint64_t transfer_bytes;
    uint64_t stream;
};

struct PipelineSlot {
    uint64_t host_pinned_ptr;
    uint64_t dev_ptr;
    uint64_t capacity_bytes;
    uint64_t stream;
    StreamFence dma_fence;
    StreamFence solve_fence;
    BufferState state;
    uint32_t generation;
};

struct PcieMetrics {
    float total_dma_ms;
    float total_solve_ms;
    float total_idle_ms;
    uint32_t dma_count;
    uint32_t solve_count;
    float bottleneck_factor;
};

struct StreamManager {
    YVec slots;
    uint32_t slot_count;
    uint32_t fill_cursor;
    uint32_t generation;
    PcieMetrics metrics;
    StreamFence dma_start_fence;
    StreamFence dma_end_fence;
    StreamFence solve_start_fence;
    StreamFence solve_end_fence;
};

StreamFence StreamFence_new(uint32_t tag);
void StreamFence_record(StreamFence* f, uint64_t stream);
bool StreamFence_query(const StreamFence* f);
void StreamFence_wait_blocking(const StreamFence* f);
float StreamFence_elapsed_ms(const StreamFence* start, const StreamFence* end);
void StreamFence_destroy(StreamFence* f);
uint64_t StreamFence_cuda_event_create(uint32_t tag);
void StreamFence_cuda_event_record(uint64_t ev, uint64_t stream);
bool StreamFence_cuda_event_query(uint64_t ev);
void StreamFence_cuda_event_synchronize(uint64_t ev);
float StreamFence_cuda_event_elapsed(uint64_t start, uint64_t end);
void StreamFence_cuda_event_destroy(uint64_t ev);
PipelineSlot Vec_get_PipelineSlot(const YVec* v, size_t i);
PcieMetrics PcieMetrics_new(void);
void PcieMetrics_update_bottleneck(PcieMetrics* m);
void PcieMetrics_print_report(const PcieMetrics* m);
StreamManager StreamManager_new(uint64_t buffer_size_bytes);
StreamHandle StreamManager_acquire_for_fill(StreamManager* sm);
StreamHandle StreamManager_submit_dma(StreamManager* sm, StreamHandle handle);
StreamHandle StreamManager_submit_solve(StreamManager* sm, StreamHandle handle);
void StreamManager_recycle(StreamManager* sm, StreamHandle handle);
void StreamManager_wait_on_gpu(const StreamManager* sm, const StreamHandle* handle);
void StreamManager_wait_on_dma(const StreamManager* sm, const StreamHandle* handle);
bool StreamManager_is_dma_done(const StreamManager* sm, const StreamHandle* handle);
bool StreamManager_is_solve_done(const StreamManager* sm, const StreamHandle* handle);
void StreamManager_run_pipeline(StreamManager* sm, const YVec* batches, uint32_t batch_count, uint64_t batch_size_bytes);
void StreamManager_destroy(StreamManager* sm);
uint64_t StreamManager_cuda_malloc_host(uint64_t bytes);
uint64_t StreamManager_cuda_malloc_device(uint64_t bytes);
void StreamManager_cuda_free_host(uint64_t ptr);
void StreamManager_cuda_free_device(uint64_t ptr);
uint64_t StreamManager_cuda_stream_create(void);
void StreamManager_cuda_stream_destroy(uint64_t s);
void StreamManager_cuda_memcpy_async_h2d(uint64_t dst, uint64_t src, uint64_t bytes, uint64_t stream);
void StreamManager_cuda_launch_kernel_on_stream(uint64_t data_ptr, uint64_t stream);
void StreamManager_memcpy_to_pinned(uint64_t dst, const YVec* src, uint32_t batch_idx, uint64_t bytes);

static const uint32_t TRIPLE_BUFFER_COUNT = 3;

static const uint64_t MAX_TILE_BYTES = 1024;

/* impl StreamFence */
StreamFence StreamFence_new(uint32_t tag) {
    StreamFence f;
    f.event_handle = StreamFence_cuda_event_create(tag);
    f.stream_handle = 0;
    f.is_recorded = false;
    f.tag = tag;
    return f;
}

void StreamFence_record(StreamFence* f, uint64_t stream) {
    (*f).stream_handle = stream;
    (*f).is_recorded = true;
    StreamFence_cuda_event_record((*f).event_handle, stream);
}

bool StreamFence_query(const StreamFence* f) {
    if (((*f).is_recorded == false)) {
        return true;
    }
    return StreamFence_cuda_event_query((*f).event_handle);
}

void StreamFence_wait_blocking(const StreamFence* f) {
    if (((*f).is_recorded == false)) {
        return;
    }
    StreamFence_cuda_event_synchronize((*f).event_handle);
}

float StreamFence_elapsed_ms(const StreamFence* start, const StreamFence* end) {
    return StreamFence_cuda_event_elapsed((*start).event_handle, (*end).event_handle);
}

void StreamFence_destroy(StreamFence* f) {
    StreamFence_cuda_event_destroy((*f).event_handle);
    (*f).event_handle = 0;
    (*f).is_recorded = false;
}

uint64_t StreamFence_cuda_event_create(uint32_t tag) {
    return 0;
}

void StreamFence_cuda_event_record(uint64_t ev, uint64_t stream) {
}

bool StreamFence_cuda_event_query(uint64_t ev) {
    return true;
}

void StreamFence_cuda_event_synchronize(uint64_t ev) {
}

float StreamFence_cuda_event_elapsed(uint64_t start, uint64_t end) {
    return 0.0;
}

void StreamFence_cuda_event_destroy(uint64_t ev) {
}

/* impl Vec */
PipelineSlot Vec_get_PipelineSlot(const YVec* v, size_t i) {
    PipelineSlot d = {0};
    return d;
}

/* impl PcieMetrics */
PcieMetrics PcieMetrics_new(void) {
    PcieMetrics m;
    m.total_dma_ms = 0.0;
    m.total_solve_ms = 0.0;
    m.total_idle_ms = 0.0;
    m.dma_count = 0;
    m.solve_count = 0;
    m.bottleneck_factor = 0.0;
    return m;
}

void PcieMetrics_update_bottleneck(PcieMetrics* m) {
    if (((*m).total_solve_ms > 0.0)) {
        (*m).bottleneck_factor = ((*m).total_idle_ms / (*m).total_solve_ms);
    } else {
        (*m).bottleneck_factor = 0.0;
    }
}

void PcieMetrics_print_report(const PcieMetrics* m) {
    printf("%s\n", (ystr_new("[sentinel] ── PCIe Bottleneck Report ──")).data);
    printf("%s", (ystr_new("  DMA transfers : ")).data);
    printf("%d\n", (int)(*m).dma_count);
    printf("%s\n", (ystr_new("")).data);
    printf("%s", (ystr_new("  Kernel launches: ")).data);
    printf("%d\n", (int)(*m).solve_count);
    printf("%s\n", (ystr_new("")).data);
    printf("%s", (ystr_new("  Bottleneck factor: ")).data);
    if (((*m).bottleneck_factor > 1.0)) {
        printf("%s\n", (ystr_new("GPU STARVED (PCIe-bound)")).data);
    } else {
        printf("%s\n", (ystr_new("COMPUTE-BOUND (healthy)")).data);
    }
}

/* impl StreamManager */
StreamManager StreamManager_new(uint64_t buffer_size_bytes) {
    StreamManager sm;
    sm.slots = yvec_new(32);
    sm.slot_count = TRIPLE_BUFFER_COUNT;
    sm.fill_cursor = 0;
    sm.generation = 0;
    sm.metrics = PcieMetrics_new();
    sm.dma_start_fence = StreamFence_new(100);
    sm.dma_end_fence = StreamFence_new(101);
    sm.solve_start_fence = StreamFence_new(200);
    sm.solve_end_fence = StreamFence_new(201);
    uint32_t i = 0;
    while ((i < TRIPLE_BUFFER_COUNT)) {
        PipelineSlot slot;
        slot.host_pinned_ptr = StreamManager_cuda_malloc_host(buffer_size_bytes);
        slot.dev_ptr = StreamManager_cuda_malloc_device(buffer_size_bytes);
        slot.capacity_bytes = buffer_size_bytes;
        slot.stream = StreamManager_cuda_stream_create();
        slot.dma_fence = StreamFence_new((i * 10));
        slot.solve_fence = StreamFence_new(((i * 10) + 1));
        slot.state = BufferState_Idle;
        slot.generation = 0;
        { __typeof__((&slot)) __push_tmp = (&slot); yvec_push((&sm.slots), &__push_tmp); };
        i += 1;
    }
    printf("%s\n", (ystr_new("[stream] Triple-buffer pool initialized (3 slots)")).data);
    return sm;
}

StreamHandle StreamManager_acquire_for_fill(StreamManager* sm) {
    uint32_t slot_idx = (*sm).fill_cursor;
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), slot_idx));
    if ((slot.state == BufferState_Solving)) {
        StreamFence_wait_blocking((&slot.solve_fence));
        slot.state = BufferState_Idle;
    }
    if ((slot.state == BufferState_Transferring)) {
        StreamFence_wait_blocking((&slot.dma_fence));
        slot.state = BufferState_Idle;
    }
    slot.state = BufferState_Filling;
    (*sm).generation += 1;
    slot.generation = (*sm).generation;
    StreamHandle handle;
    handle.slot_index = slot_idx;
    handle.state = BufferState_Filling;
    handle.generation = (*sm).generation;
    handle.host_pinned_ptr = slot.host_pinned_ptr;
    handle.dev_ptr = slot.dev_ptr;
    handle.transfer_bytes = 0;
    handle.stream = slot.stream;
    (*sm).fill_cursor = ((slot_idx + 1) % TRIPLE_BUFFER_COUNT);
    return handle;
}

StreamHandle StreamManager_submit_dma(StreamManager* sm, StreamHandle handle) {
    uint32_t idx = handle.slot_index;
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), idx));
    StreamFence_record((&(*sm).dma_start_fence), slot.stream);
    StreamManager_cuda_memcpy_async_h2d(slot.dev_ptr, slot.host_pinned_ptr, handle.transfer_bytes, slot.stream);
    StreamFence_record((&slot.dma_fence), slot.stream);
    StreamFence_record((&(*sm).dma_end_fence), slot.stream);
    slot.state = BufferState_Transferring;
    StreamHandle new_handle;
    new_handle.slot_index = idx;
    new_handle.state = BufferState_Transferring;
    new_handle.generation = handle.generation;
    new_handle.host_pinned_ptr = slot.host_pinned_ptr;
    new_handle.dev_ptr = slot.dev_ptr;
    new_handle.transfer_bytes = handle.transfer_bytes;
    new_handle.stream = slot.stream;
    return new_handle;
}

StreamHandle StreamManager_submit_solve(StreamManager* sm, StreamHandle handle) {
    uint32_t idx = handle.slot_index;
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), idx));
    StreamFence_record((&(*sm).solve_start_fence), slot.stream);
    StreamManager_cuda_launch_kernel_on_stream(slot.dev_ptr, slot.stream);
    StreamFence_record((&slot.solve_fence), slot.stream);
    StreamFence_record((&(*sm).solve_end_fence), slot.stream);
    slot.state = BufferState_Solving;
    StreamHandle new_handle;
    new_handle.slot_index = idx;
    new_handle.state = BufferState_Solving;
    new_handle.generation = handle.generation;
    new_handle.host_pinned_ptr = slot.host_pinned_ptr;
    new_handle.dev_ptr = slot.dev_ptr;
    new_handle.transfer_bytes = handle.transfer_bytes;
    new_handle.stream = slot.stream;
    return new_handle;
}

void StreamManager_recycle(StreamManager* sm, StreamHandle handle) {
    uint32_t idx = handle.slot_index;
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), idx));
    StreamFence_wait_blocking((&slot.solve_fence));
    float dma_ms = StreamFence_elapsed_ms((&(*sm).dma_start_fence), (&(*sm).dma_end_fence));
    float solve_ms = StreamFence_elapsed_ms((&(*sm).solve_start_fence), (&(*sm).solve_end_fence));
    (*sm).metrics.total_dma_ms += dma_ms;
    (*sm).metrics.total_solve_ms += solve_ms;
    (*sm).metrics.dma_count += 1;
    (*sm).metrics.solve_count += 1;
    if ((dma_ms > solve_ms)) {
        (*sm).metrics.total_idle_ms += (dma_ms - solve_ms);
    }
    PcieMetrics_update_bottleneck((&(*sm).metrics));
    slot.state = BufferState_Idle;
}

void StreamManager_wait_on_gpu(const StreamManager* sm, const StreamHandle* handle) {
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), handle->slot_index));
    StreamFence_wait_blocking((&slot.solve_fence));
}

void StreamManager_wait_on_dma(const StreamManager* sm, const StreamHandle* handle) {
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), handle->slot_index));
    StreamFence_wait_blocking((&slot.dma_fence));
}

bool StreamManager_is_dma_done(const StreamManager* sm, const StreamHandle* handle) {
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), handle->slot_index));
    return StreamFence_query((&slot.dma_fence));
}

bool StreamManager_is_solve_done(const StreamManager* sm, const StreamHandle* handle) {
    PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), handle->slot_index));
    return StreamFence_query((&slot.solve_fence));
}

void StreamManager_run_pipeline(StreamManager* sm, const YVec* batches, uint32_t batch_count, uint64_t batch_size_bytes) {
    printf("%s\n", (ystr_new("[stream] Starting triple-buffered pipeline")).data);
    printf("%s", (ystr_new("[stream]   Batches: ")).data);
    printf("%d\n", (int)batch_count);
    printf("%s\n", (ystr_new("")).data);
    bool h0_valid = false;
    bool h1_valid = false;
    StreamHandle h0;
    StreamHandle h1;
    h0.slot_index = 0;
    h0.state = BufferState_Idle;
    h0.generation = 0;
    h0.host_pinned_ptr = 0;
    h0.dev_ptr = 0;
    h0.transfer_bytes = 0;
    h0.stream = 0;
    h1 = h0;
    uint32_t batch_idx = 0;
    while ((batch_idx < batch_count)) {
        StreamHandle h_fill = StreamManager_acquire_for_fill(sm);
        h_fill.transfer_bytes = batch_size_bytes;
        StreamManager_memcpy_to_pinned(h_fill.host_pinned_ptr, batches, batch_idx, batch_size_bytes);
        StreamHandle h_dma = StreamManager_submit_dma(sm, h_fill);
        if (h1_valid) {
            StreamHandle h_solve = StreamManager_submit_solve(sm, h1);
            if (h0_valid) {
                StreamManager_recycle(sm, h0);
            }
            h0 = h_solve;
            h0_valid = true;
        }
        h1 = h_dma;
        h1_valid = true;
        batch_idx += 1;
    }
    if (h1_valid) {
        StreamHandle h_solve = StreamManager_submit_solve(sm, h1);
        if (h0_valid) {
            StreamManager_recycle(sm, h0);
        }
        StreamManager_recycle(sm, h_solve);
    } else     if (h0_valid) {
        StreamManager_recycle(sm, h0);
    }
    printf("%s\n", (ystr_new("[stream] Pipeline complete")).data);
    PcieMetrics_print_report((&(*sm).metrics));
}

void StreamManager_destroy(StreamManager* sm) {
    uint32_t i = 0;
    while ((i < (*sm).slot_count)) {
        PipelineSlot slot = (*(PipelineSlot*)yvec_get((&(*sm).slots), i));
        StreamManager_cuda_free_host(slot.host_pinned_ptr);
        StreamManager_cuda_free_device(slot.dev_ptr);
        StreamManager_cuda_stream_destroy(slot.stream);
        StreamFence_destroy((&slot.dma_fence));
        StreamFence_destroy((&slot.solve_fence));
        i += 1;
    }
    StreamFence_destroy((&(*sm).dma_start_fence));
    StreamFence_destroy((&(*sm).dma_end_fence));
    StreamFence_destroy((&(*sm).solve_start_fence));
    StreamFence_destroy((&(*sm).solve_end_fence));
    printf("%s\n", (ystr_new("[stream] All resources released")).data);
}

uint64_t StreamManager_cuda_malloc_host(uint64_t bytes) {
    return 0;
}

uint64_t StreamManager_cuda_malloc_device(uint64_t bytes) {
    return 0;
}

void StreamManager_cuda_free_host(uint64_t ptr) {
}

void StreamManager_cuda_free_device(uint64_t ptr) {
}

uint64_t StreamManager_cuda_stream_create(void) {
    return 0;
}

void StreamManager_cuda_stream_destroy(uint64_t s) {
}

void StreamManager_cuda_memcpy_async_h2d(uint64_t dst, uint64_t src, uint64_t bytes, uint64_t stream) {
}

void StreamManager_cuda_launch_kernel_on_stream(uint64_t data_ptr, uint64_t stream) {
}

void StreamManager_memcpy_to_pinned(uint64_t dst, const YVec* src, uint32_t batch_idx, uint64_t bytes) {
}


/* -- Source: bcp_engine.c -- */



typedef struct ConflictRecord ConflictRecord;
typedef struct LearnedClause LearnedClause;
typedef struct BcpEngine BcpEngine;

struct ConflictRecord {
    uint32_t clause_row;
    uint32_t conflict_var;
    uint32_t ballot_mask;
    uint32_t iteration;
};

struct LearnedClause {
    uint32_t lit_start;
    uint32_t lit_count;
    uint32_t backtrack_level;
};

struct BcpEngine {
    YVec assignments;
    uint32_t num_variables;
    uint32_t decision_level;
    YVec conflicts;
    uint32_t conflict_count;
    YVec learned;
    uint32_t learned_count;
    YVec prop_queue;
    uint32_t prop_head;
    uint32_t prop_tail;
    uint32_t iteration;
};

typedef enum {
    ClauseState_TAG_Satisfied,
    ClauseState_TAG_Unsatisfied,
    ClauseState_TAG_Unit,
    ClauseState_TAG_Unresolved
} ClauseState_Tag;

typedef struct {
    uint32_t _0;
} ClauseState_Unit_Data;

typedef struct {
    ClauseState_Tag tag;
    union {
        ClauseState_Unit_Data Unit;
    } data;
} ClauseState;

#define ClauseState_Satisfied ((ClauseState){ .tag = ClauseState_TAG_Satisfied })
#define ClauseState_Unsatisfied ((ClauseState){ .tag = ClauseState_TAG_Unsatisfied })
static inline ClauseState ClauseState_Unit(uint32_t _0) {
    ClauseState res;
    res.tag = ClauseState_TAG_Unit;
    res.data.Unit._0 = _0;
    return res;
}

#define ClauseState_Unresolved ((ClauseState){ .tag = ClauseState_TAG_Unresolved })
ConflictRecord Vec_get_ConflictRecord(const YVec* v, size_t i);
ClauseState Vec_get_ClauseState(const YVec* v, size_t i);
LearnedClause Vec_get_LearnedClause(const YVec* v, size_t i);
BcpEngine BcpEngine_new(uint32_t num_vars);
void BcpEngine_threshold_evaluate(BcpEngine* bcp, const AccumulatorTile* acc, uint32_t num_clauses, uint32_t num_vars, YVec* out_states);
LearnedClause BcpEngine_cdcl_analyze(BcpEngine* bcp, const AccumulatorTile* acc, uint32_t conflict_clause, uint32_t num_vars);
bool BcpEngine_propagate(BcpEngine* bcp);
int32_t BcpEngine_read_acc_i32(const BcpEngine* bcp, uint64_t base, uint64_t row_off, uint32_t col);
uint32_t BcpEngine_get_lane_id(const BcpEngine* bcp);
uint32_t BcpEngine_ballot_sync(const BcpEngine* bcp, uint32_t mask, bool predicate);
uint32_t BcpEngine_find_first_set(const BcpEngine* bcp, uint32_t mask);

static const uint32_t FULL_WARP_MASK = 4294967295;

static const uint32_t BCP_WARP_SIZE = 32;

/* impl Vec */
ConflictRecord Vec_get_ConflictRecord(const YVec* v, size_t i) {
    ConflictRecord d = {0};
    return d;
}

ClauseState Vec_get_ClauseState(const YVec* v, size_t i) {
    ClauseState d = {0};
    return d;
}

/* impl Vec */
LearnedClause Vec_get_LearnedClause(const YVec* v, size_t i) {
    LearnedClause d = {0};
    return d;
}

/* impl BcpEngine */
BcpEngine BcpEngine_new(uint32_t num_vars) {
    BcpEngine bcp;
    bcp.assignments = yvec_new(1);
    bcp.num_variables = num_vars;
    uint32_t i = 0;
    while ((i < num_vars)) {
        int8_t unassigned = (-1);
        { __typeof__((&unassigned)) __push_tmp = (&unassigned); yvec_push((&bcp.assignments), &__push_tmp); };
        i += 1;
    }
    bcp.decision_level = 0;
    bcp.conflicts = yvec_new(16);
    bcp.conflict_count = 0;
    bcp.learned = yvec_new(8);
    bcp.learned_count = 0;
    bcp.prop_queue = yvec_new(8);
    bcp.prop_head = 0;
    bcp.prop_tail = 0;
    bcp.iteration = 0;
    return bcp;
}

void BcpEngine_threshold_evaluate(BcpEngine* bcp, const AccumulatorTile* acc, uint32_t num_clauses, uint32_t num_vars, YVec* out_states) {
    uint32_t clause = 0;
    while ((clause < num_clauses)) {
        uint64_t row_base = ((clause * (*acc).ld) * 4);
        int32_t row_sum = 0;
        uint32_t unassigned_count = 0;
        uint32_t last_unassigned = 0;
        uint32_t col = 0;
        while ((col < num_vars)) {
            int32_t val = BcpEngine_read_acc_i32(bcp, (*acc).dev_ptr, row_base, col);
            if ((val > 0)) {
                row_sum += val;
            }
            int8_t assign = (*(int8_t*)yvec_get((&(*bcp).assignments), col));
            if ((assign == (-1))) {
                unassigned_count += 1;
                last_unassigned = col;
            }
            col += 1;
        }
        ClauseState state;
        if ((row_sum > 0)) {
            state = ClauseState_Satisfied;
        } else         if ((unassigned_count == 0)) {
            state = ClauseState_Unsatisfied;
            ConflictRecord cr;
            cr.clause_row = clause;
            cr.conflict_var = 0;
            cr.ballot_mask = 0;
            cr.iteration = (*bcp).iteration;
            { __typeof__((&cr)) __push_tmp = (&cr); yvec_push((&(*bcp).conflicts), &__push_tmp); };
            (*bcp).conflict_count += 1;
        } else         if ((unassigned_count == 1)) {
            state = ClauseState_Unit(last_unassigned);
            { __typeof__((&last_unassigned)) __push_tmp = (&last_unassigned); yvec_push((&(*bcp).prop_queue), &__push_tmp); };
            (*bcp).prop_tail += 1;
        } else {
            state = ClauseState_Unresolved;
        }
        { __typeof__((&state)) __push_tmp = (&state); yvec_push(out_states, &__push_tmp); };
        clause += 1;
    }
}

LearnedClause BcpEngine_cdcl_analyze(BcpEngine* bcp, const AccumulatorTile* acc, uint32_t conflict_clause, uint32_t num_vars) {
    uint64_t row_base = ((conflict_clause * (*acc).ld) * 4);
    uint32_t lane_id = BcpEngine_get_lane_id(bcp);
    uint32_t my_var = lane_id;
    int32_t my_contribution = 0;
    if ((my_var < num_vars)) {
        my_contribution = BcpEngine_read_acc_i32(bcp, (*acc).dev_ptr, row_base, my_var);
    }
    bool is_conflict_origin = ((my_contribution == 0) && (my_var < num_vars));
    uint32_t ballot_result = BcpEngine_ballot_sync(bcp, FULL_WARP_MASK, is_conflict_origin);
    uint32_t conflict_var = BcpEngine_find_first_set(bcp, ballot_result);
    LearnedClause lc;
    lc.lit_start = (*bcp).learned_count;
    lc.lit_count = 1;
    lc.backtrack_level = ((*bcp).decision_level - 1);
    { __typeof__((&lc)) __push_tmp = (&lc); yvec_push((&(*bcp).learned), &__push_tmp); };
    (*bcp).learned_count += 1;
    int8_t falsified = 0;
    Vec_set_I8((&(*bcp).assignments), conflict_var, falsified);
    ConflictRecord cr;
    cr.clause_row = conflict_clause;
    cr.conflict_var = conflict_var;
    cr.ballot_mask = ballot_result;
    cr.iteration = (*bcp).iteration;
    { __typeof__((&cr)) __push_tmp = (&cr); yvec_push((&(*bcp).conflicts), &__push_tmp); };
    (*bcp).conflict_count += 1;
    return lc;
}

bool BcpEngine_propagate(BcpEngine* bcp) {
    bool made_progress = false;
    while (((*bcp).prop_head < (*bcp).prop_tail)) {
        uint32_t var = (*(uint32_t*)yvec_get((&(*bcp).prop_queue), (*bcp).prop_head));
        (*bcp).prop_head += 1;
        int8_t current = (*(int8_t*)yvec_get((&(*bcp).assignments), var));
        if ((current == (-1))) {
            int8_t one = 1;
            Vec_set_I8((&(*bcp).assignments), var, one);
            made_progress = true;
        }
    }
    return made_progress;
}

int32_t BcpEngine_read_acc_i32(const BcpEngine* bcp, uint64_t base, uint64_t row_off, uint32_t col) {
    return 0;
}

uint32_t BcpEngine_get_lane_id(const BcpEngine* bcp) {
    return 0;
}

uint32_t BcpEngine_ballot_sync(const BcpEngine* bcp, uint32_t mask, bool predicate) {
    return 0;
}

uint32_t BcpEngine_find_first_set(const BcpEngine* bcp, uint32_t mask) {
    return 0;
}


/* -- Source: booledass.c -- */



typedef struct SolverConfig SolverConfig;

struct SolverConfig {
    uint32_t max_iterations;
    uint64_t vram_budget;
    bool enable_cdcl;
    bool enable_aig_prune;
    int32_t tile_m;
    int32_t tile_n;
    int32_t tile_k;
};

typedef enum {
    SatResult_TAG_Satisfiable,
    SatResult_TAG_Unsatisfiable,
    SatResult_TAG_Unknown
} SatResult_Tag;

typedef struct {
    YVec _0;
} SatResult_Satisfiable_Data;

typedef struct {
    uint32_t _0;
} SatResult_Unknown_Data;

typedef struct {
    SatResult_Tag tag;
    union {
        SatResult_Satisfiable_Data Satisfiable;
        SatResult_Unknown_Data Unknown;
    } data;
} SatResult;

static inline SatResult SatResult_Satisfiable(YVec _0) {
    SatResult res;
    res.tag = SatResult_TAG_Satisfiable;
    res.data.Satisfiable._0 = _0;
    return res;
}

#define SatResult_Unsatisfiable ((SatResult){ .tag = SatResult_TAG_Unsatisfiable })
static inline SatResult SatResult_Unknown(uint32_t _0) {
    SatResult res;
    res.tag = SatResult_TAG_Unknown;
    res.data.Unknown._0 = _0;
    return res;
}

SolverConfig SolverConfig_default(void);
int booledass_solve(unsigned num_vars, unsigned num_clauses, const int8_t* matrix_data);

static const int32_t TILE_M = 16;

static const int32_t TILE_N = 8;

static const int32_t TILE_K = 16;

static const int32_t SOLVER_WARP_SIZE = 32;

static const uint32_t FULL_MASK = 4294967295;

static const int32_t SAT_TRUE = 1;

static const int32_t SAT_FALSE = 0;

static const int32_t SAT_UNDEF = (-1);

static const uint64_t VRAM_BUDGET_BYTES = 268435456;

/* impl SolverConfig */
SolverConfig SolverConfig_default(void) {
    SolverConfig cfg = {0};
    cfg.max_iterations = 4096;
    cfg.vram_budget = VRAM_BUDGET_BYTES;
    cfg.enable_cdcl = true;
    cfg.enable_aig_prune = true;
    cfg.tile_m = TILE_M;
    cfg.tile_n = TILE_N;
    cfg.tile_k = TILE_K;
    return cfg;
}

/* Extern declaration for the real GPU BCP solver (in booledass_kernels.cu) */
extern int gpu_bcp_solve(const int8_t* host_matrix, uint32_t num_vars, uint32_t num_clauses);

int booledass_solve(unsigned num_vars, unsigned num_clauses, const int8_t* matrix_data) {
    printf("[booledass] GPU SAT intercept: %u vars, %u clauses\n", num_vars, num_clauses);

    if (num_clauses == 0 || num_vars == 0) {
        printf("[booledass] Trivial instance, returning UNDEF\n");
        return SAT_UNDEF;
    }

    /* Call the real CUDA BCP solver */
    int gpu_result = gpu_bcp_solve(matrix_data, num_vars, num_clauses);

    if (gpu_result == 1) {
        printf("[booledass] >>> GPU BCP: SATISFIABLE\n");
        return SAT_TRUE;
    } else if (gpu_result == 0) {
        printf("[booledass] >>> GPU BCP: UNSATISFIABLE (conflict)\n");
        return SAT_FALSE;
    } else {
        printf("[booledass] >>> GPU BCP: UNDETERMINED -> CPU CDCL fallback\n");
        return SAT_UNDEF;
    }
}

